/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fet;

import java.awt.Color;
import fet.JDBC.*;
import fet.Register;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pharaoh
 */
public class Admin extends javax.swing.JFrame {
    
    JDBC j = new JDBC();
    Register r = new Register();
    
  Color R;
  
    public Admin() {
        initComponents();
        jLabel1.setVisible(true);
        jLabel2.setVisible(false);
        R=jLabel9. getBackground();
        collapsedbar.setVisible(false);
        expandedbar.setVisible(true);
        jPanel4.setVisible(false);
        r.reg = true;
        r.reg2 = true;
        student.setVisible(false);
        homepanel.setVisible(true);
        addpanel.setVisible(false);
        admin.setVisible(false);
        instructor.setVisible(false);
        exampanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        expandedbar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        examLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        collapsedbar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        add_inst = new javax.swing.JLabel();
        add_stud = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        homepanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btn_stud = new javax.swing.JButton();
        btn_inst = new javax.swing.JButton();
        examBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        exampanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studTable = new javax.swing.JTable();
        openBtn = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        sessionTable = new javax.swing.JTable();
        instructor = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        req_table = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        inst_list = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        add_ins = new javax.swing.JButton();
        del_ins = new javax.swing.JButton();
        student = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        stud_req = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        stud_list = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        addstud = new javax.swing.JButton();
        delstud = new javax.swing.JButton();
        addpanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        admin = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        admin_name = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        add_admin = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        admin_pass = new javax.swing.JPasswordField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        expandedbar.setBackground(new java.awt.Color(39, 42, 54));
        expandedbar.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin");
        expandedbar.add(jLabel1);
        jLabel1.setBounds(0, 0, 90, 40);

        jLabel5.setBackground(new java.awt.Color(39, 42, 54));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fet/Images/add (2).png"))); // NOI18N
        jLabel5.setText("   Add");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel5.setFocusable(false);
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        expandedbar.add(jLabel5);
        jLabel5.setBounds(10, 210, 190, 60);

        jLabel7.setBackground(new java.awt.Color(39, 42, 54));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fet/Images/home-icon-silhouette.png"))); // NOI18N
        jLabel7.setText("   Home");
        jLabel7.setFocusable(false);
        jLabel7.setOpaque(true);
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel7MouseExited(evt);
            }
        });
        expandedbar.add(jLabel7);
        jLabel7.setBounds(10, 150, 190, 60);

        jLabel9.setBackground(new java.awt.Color(39, 42, 54));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fet/Images/menu.png"))); // NOI18N
        jLabel9.setFocusable(false);
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel9MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });
        expandedbar.add(jLabel9);
        jLabel9.setBounds(160, 0, 40, 40);

        examLabel.setBackground(new java.awt.Color(39, 42, 54));
        examLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        examLabel.setForeground(new java.awt.Color(255, 255, 255));
        examLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fet/Images/test (5).png"))); // NOI18N
        examLabel.setText("   Exam Session");
        examLabel.setFocusable(false);
        examLabel.setOpaque(true);
        examLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                examLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                examLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                examLabelMouseExited(evt);
            }
        });
        expandedbar.add(examLabel);
        examLabel.setBounds(10, 270, 190, 60);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fet/Images/logout.png"))); // NOI18N
        jLabel13.setText("  Log Out");
        expandedbar.add(jLabel13);
        jLabel13.setBounds(10, 710, 190, 60);

        getContentPane().add(expandedbar);
        expandedbar.setBounds(0, 0, 200, 770);

        collapsedbar.setBackground(new java.awt.Color(39, 42, 54));
        collapsedbar.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(39, 42, 54));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fet/Images/home-icon-silhouette (2).png"))); // NOI18N
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        collapsedbar.add(jLabel3);
        jLabel3.setBounds(0, 160, 80, 60);

        jLabel8.setBackground(new java.awt.Color(39, 42, 54));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fet/Images/add (3).png"))); // NOI18N
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel8MouseExited(evt);
            }
        });
        collapsedbar.add(jLabel8);
        jLabel8.setBounds(0, 220, 80, 60);

        jLabel10.setBackground(new java.awt.Color(39, 42, 54));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fet/Images/test (6).png"))); // NOI18N
        jLabel10.setOpaque(true);
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel10MouseExited(evt);
            }
        });
        collapsedbar.add(jLabel10);
        jLabel10.setBounds(0, 280, 80, 60);

        jLabel11.setBackground(new java.awt.Color(39, 42, 54));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fet/Images/menu (1).png"))); // NOI18N
        jLabel11.setOpaque(true);
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel11MouseExited(evt);
            }
        });
        collapsedbar.add(jLabel11);
        jLabel11.setBounds(0, 0, 80, 40);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fet/Images/logout.png"))); // NOI18N
        collapsedbar.add(jLabel12);
        jLabel12.setBounds(0, 710, 80, 60);

        getContentPane().add(collapsedbar);
        collapsedbar.setBounds(0, 0, 80, 770);

        jLabel2.setBackground(new java.awt.Color(39, 42, 54));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Admin");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 0, 80, 40);

        jPanel4.setBackground(new java.awt.Color(39, 42, 54));
        jPanel4.setLayout(null);

        add_inst.setBackground(new java.awt.Color(39, 42, 54));
        add_inst.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add_inst.setForeground(new java.awt.Color(255, 255, 255));
        add_inst.setText("Add Instructor");
        add_inst.setOpaque(true);
        add_inst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_instMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_instMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_instMouseExited(evt);
            }
        });
        jPanel4.add(add_inst);
        add_inst.setBounds(0, 50, 170, 50);

        add_stud.setBackground(new java.awt.Color(39, 42, 54));
        add_stud.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add_stud.setForeground(new java.awt.Color(255, 255, 255));
        add_stud.setText("Add Student");
        add_stud.setOpaque(true);
        add_stud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_studMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_studMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_studMouseExited(evt);
            }
        });
        jPanel4.add(add_stud);
        add_stud.setBounds(0, 100, 170, 50);

        jLabel4.setBackground(new java.awt.Color(39, 42, 54));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Add Admin");
        jLabel4.setOpaque(true);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel4.add(jLabel4);
        jLabel4.setBounds(0, 0, 170, 50);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(200, 210, 170, 150);

        homepanel.setBackground(new java.awt.Color(255, 255, 255));
        homepanel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        homepanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homepanelMouseEntered(evt);
            }
        });
        homepanel.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        btn_stud.setBackground(new java.awt.Color(51, 255, 51));
        btn_stud.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_stud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fet/Images/graduate-student-avatar.png"))); // NOI18N
        btn_stud.setText("Student");
        btn_stud.setFocusable(false);
        btn_stud.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_stud.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_stud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_studMouseClicked(evt);
            }
        });
        jPanel1.add(btn_stud);
        btn_stud.setBounds(690, 90, 280, 250);

        btn_inst.setBackground(new java.awt.Color(0, 153, 255));
        btn_inst.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_inst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fet/Images/instructor-lecture-with-sceen-projection-tool.png"))); // NOI18N
        btn_inst.setText("Instructor");
        btn_inst.setFocusable(false);
        btn_inst.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_inst.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_inst.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_instMouseClicked(evt);
            }
        });
        btn_inst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_instActionPerformed(evt);
            }
        });
        jPanel1.add(btn_inst);
        btn_inst.setBounds(370, 90, 280, 250);

        examBtn.setBackground(new java.awt.Color(255, 255, 0));
        examBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        examBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fet/Images/test1.png"))); // NOI18N
        examBtn.setText("Exam Session");
        examBtn.setFocusable(false);
        examBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        examBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        examBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                examBtnMouseClicked(evt);
            }
        });
        examBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examBtnActionPerformed(evt);
            }
        });
        jPanel1.add(examBtn);
        examBtn.setBounds(30, 90, 280, 250);

        homepanel.add(jPanel1);
        jPanel1.setBounds(230, 230, 1030, 440);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fet/Images/question (2).png"))); // NOI18N
        jLabel14.setOpaque(true);
        homepanel.add(jLabel14);
        jLabel14.setBounds(610, 230, 290, 310);

        jLabel15.setBackground(new java.awt.Color(255, 153, 153));
        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setOpaque(true);
        homepanel.add(jLabel15);
        jLabel15.setBounds(430, 170, 610, 50);

        getContentPane().add(homepanel);
        homepanel.setBounds(0, 0, 1370, 770);

        exampanel.setBackground(new java.awt.Color(255, 255, 255));
        exampanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exampanelMouseEntered(evt);
            }
        });
        exampanel.setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseEntered(evt);
            }
        });

        studTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        studTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Names"
            }
        ));
        studTable.setFocusable(false);
        studTable.setGridColor(new java.awt.Color(255, 255, 255));
        studTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        studTable.setRowHeight(30);
        studTable.setSelectionBackground(new java.awt.Color(255, 255, 0));
        studTable.setShowHorizontalLines(false);
        studTable.setShowVerticalLines(false);
        jScrollPane1.setViewportView(studTable);

        exampanel.add(jScrollPane1);
        jScrollPane1.setBounds(340, 220, 880, 200);

        openBtn.setText("Open");
        openBtn.setToolTipText("");
        openBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBtnActionPerformed(evt);
            }
        });
        exampanel.add(openBtn);
        openBtn.setBounds(680, 540, 100, 30);

        jButton9.setText("Create");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        exampanel.add(jButton9);
        jButton9.setBounds(650, 480, 160, 40);

        jScrollPane7.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jScrollPane7MouseEntered(evt);
            }
        });

        sessionTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        sessionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Exam ID", "Acceptance"
            }
        ));
        sessionTable.setFocusable(false);
        sessionTable.setGridColor(new java.awt.Color(255, 255, 255));
        sessionTable.setIntercellSpacing(new java.awt.Dimension(0, 0));
        sessionTable.setRowHeight(30);
        sessionTable.setSelectionBackground(new java.awt.Color(255, 255, 0));
        sessionTable.setShowHorizontalLines(false);
        sessionTable.setShowVerticalLines(false);
        jScrollPane7.setViewportView(sessionTable);

        exampanel.add(jScrollPane7);
        jScrollPane7.setBounds(340, 10, 880, 200);

        getContentPane().add(exampanel);
        exampanel.setBounds(0, 0, 1370, 770);

        instructor.setBackground(new java.awt.Color(255, 255, 255));
        instructor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                instructorMouseEntered(evt);
            }
        });
        instructor.setLayout(null);

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        req_table.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        req_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        req_table.setFocusable(false);
        req_table.setGridColor(new java.awt.Color(255, 255, 255));
        req_table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        req_table.setRowHeight(30);
        req_table.setSelectionBackground(new java.awt.Color(0, 204, 204));
        req_table.setSelectionForeground(new java.awt.Color(0, 0, 0));
        req_table.setShowHorizontalLines(false);
        req_table.setShowVerticalLines(false);
        req_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                req_tableMouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(req_table);

        instructor.add(jScrollPane4);
        jScrollPane4.setBounds(210, 100, 1010, 290);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));

        inst_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mail"
            }
        ));
        inst_list.setEnabled(false);
        inst_list.setFocusable(false);
        inst_list.setGridColor(new java.awt.Color(255, 255, 255));
        inst_list.setIntercellSpacing(new java.awt.Dimension(0, 0));
        inst_list.setRowHeight(30);
        inst_list.setSelectionBackground(new java.awt.Color(0, 204, 204));
        inst_list.setSelectionForeground(new java.awt.Color(0, 0, 0));
        inst_list.setShowHorizontalLines(false);
        inst_list.setShowVerticalLines(false);
        jScrollPane3.setViewportView(inst_list);

        instructor.add(jScrollPane3);
        jScrollPane3.setBounds(210, 460, 1010, 300);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Instructors List :");
        instructor.add(jLabel19);
        jLabel19.setBounds(210, 420, 160, 40);

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Request List :");
        instructor.add(jLabel20);
        jLabel20.setBounds(210, 60, 130, 40);

        add_ins.setText("Add");
        add_ins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_insActionPerformed(evt);
            }
        });
        instructor.add(add_ins);
        add_ins.setBounds(1270, 170, 110, 70);

        del_ins.setText("Delete");
        del_ins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                del_insActionPerformed(evt);
            }
        });
        instructor.add(del_ins);
        del_ins.setBounds(1270, 280, 110, 70);

        getContentPane().add(instructor);
        instructor.setBounds(0, 0, 1370, 770);

        student.setBackground(new java.awt.Color(255, 255, 255));
        student.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentMouseEntered(evt);
            }
        });
        student.setLayout(null);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseEntered(evt);
            }
        });

        stud_req.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stud_req.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mail"
            }
        ));
        stud_req.setFocusable(false);
        stud_req.setGridColor(new java.awt.Color(255, 255, 255));
        stud_req.setIntercellSpacing(new java.awt.Dimension(0, 0));
        stud_req.setRowHeight(30);
        stud_req.setSelectionBackground(new java.awt.Color(0, 204, 51));
        stud_req.setSelectionForeground(new java.awt.Color(0, 0, 0));
        stud_req.setShowHorizontalLines(false);
        stud_req.setShowVerticalLines(false);
        jScrollPane2.setViewportView(stud_req);

        student.add(jScrollPane2);
        jScrollPane2.setBounds(210, 120, 1030, 250);

        stud_list.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stud_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Mail"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stud_list.setFocusable(false);
        stud_list.setIntercellSpacing(new java.awt.Dimension(0, 0));
        stud_list.setRowHeight(30);
        stud_list.setSelectionBackground(new java.awt.Color(0, 204, 51));
        stud_list.setShowHorizontalLines(false);
        stud_list.setShowVerticalLines(false);
        stud_list.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(stud_list);

        student.add(jScrollPane5);
        jScrollPane5.setBounds(210, 470, 1030, 280);

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Request List : ");
        student.add(jLabel21);
        jLabel21.setBounds(210, 60, 140, 30);

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setText("Students List :");
        student.add(jLabel22);
        jLabel22.setBounds(210, 430, 140, 40);

        addstud.setText("Add");
        addstud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudActionPerformed(evt);
            }
        });
        student.add(addstud);
        addstud.setBounds(1270, 170, 110, 70);

        delstud.setText("Delete");
        delstud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delstudActionPerformed(evt);
            }
        });
        student.add(delstud);
        delstud.setBounds(1270, 280, 110, 70);

        getContentPane().add(student);
        student.setBounds(0, 0, 1370, 770);

        addpanel.setBackground(new java.awt.Color(255, 255, 255));
        addpanel.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 0, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fet/Images/admin-with-cogwheels (1).png"))); // NOI18N
        jButton1.setText("Admin");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setMargin(new java.awt.Insets(10, 14, 2, 14));
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        addpanel.add(jButton1);
        jButton1.setBounds(320, 210, 280, 250);

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fet/Images/instructor-lecture-with-sceen-projection-tool.png"))); // NOI18N
        jButton2.setText("Instructor");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        addpanel.add(jButton2);
        jButton2.setBounds(640, 210, 280, 250);

        jButton3.setBackground(new java.awt.Color(0, 204, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fet/Images/graduate-student-avatar.png"))); // NOI18N
        jButton3.setText("Student");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        addpanel.add(jButton3);
        jButton3.setBounds(960, 210, 280, 250);

        getContentPane().add(addpanel);
        addpanel.setBounds(0, 0, 1370, 770);

        admin.setBackground(new java.awt.Color(255, 255, 255));
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                adminMouseEntered(evt);
            }
        });
        admin.setLayout(null);

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Username");
        admin.add(jLabel16);
        jLabel16.setBounds(500, 80, 80, 30);
        admin.add(admin_name);
        admin_name.setBounds(500, 120, 300, 40);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Passwrod");
        admin.add(jLabel17);
        jLabel17.setBounds(500, 170, 80, 30);

        add_admin.setBackground(new java.awt.Color(39, 42, 54));
        add_admin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add_admin.setForeground(new java.awt.Color(255, 255, 255));
        add_admin.setText("Add Admin");
        add_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_adminActionPerformed(evt);
            }
        });
        admin.add(add_admin);
        add_admin.setBounds(500, 280, 300, 60);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fet/Images/show-password.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel18MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel18MouseExited(evt);
            }
        });
        admin.add(jLabel18);
        jLabel18.setBounds(800, 210, 40, 40);

        admin_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_passActionPerformed(evt);
            }
        });
        admin.add(admin_pass);
        admin_pass.setBounds(500, 210, 300, 40);

        jTable5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable5.setGridColor(new java.awt.Color(255, 255, 255));
        jTable5.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jTable5.setSelectionBackground(new java.awt.Color(255, 0, 102));
        jTable5.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jTable5.setShowHorizontalLines(false);
        jTable5.setShowVerticalLines(false);
        jScrollPane6.setViewportView(jTable5);

        admin.add(jScrollPane6);
        jScrollPane6.setBounds(250, 470, 870, 290);

        getContentPane().add(admin);
        admin.setBounds(0, 0, 1370, 770);

        setSize(new java.awt.Dimension(1382, 808));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        
        jLabel9.setBackground(Color.DARK_GRAY);
        
    }//GEN-LAST:event_jLabel9MouseEntered

    private void jLabel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseExited
       jLabel9.setBackground(R);
    }//GEN-LAST:event_jLabel9MouseExited

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jPanel4.setVisible(true);
        jPanel4.setLocation(200, 210);
        jLabel5.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed
        //jPanel1.setSize(28, 770);
         
         jLabel1.setVisible(false);
         jLabel2.setVisible(true);
         expandedbar.setVisible(false);
         collapsedbar.setVisible(true);
    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseEntered
        jPanel4.setVisible(false);
        jLabel7.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_jLabel7MouseEntered

    private void jLabel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseExited
        jLabel7.setBackground(R);
    }//GEN-LAST:event_jLabel7MouseExited

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        
        jLabel5.setBackground(R);
    }//GEN-LAST:event_jLabel5MouseExited

    private void examLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examLabelMouseEntered
          jPanel4.setVisible(false);
        examLabel.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_examLabelMouseEntered

    private void examLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examLabelMouseExited
        examLabel.setBackground(R);
    }//GEN-LAST:event_examLabelMouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
         jPanel4.setVisible(false);
        jLabel3.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
         jLabel3.setBackground(R);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseEntered
       jPanel4.setVisible(true);
       jPanel4.setLocation(80,220);
        jLabel8.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_jLabel8MouseEntered

    private void jLabel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseExited
       
        jLabel8.setBackground(R);
    }//GEN-LAST:event_jLabel8MouseExited

    private void jLabel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseEntered
         jPanel4.setVisible(false);
        jLabel10.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_jLabel10MouseEntered

    private void jLabel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseExited
         jLabel10.setBackground(R);
    }//GEN-LAST:event_jLabel10MouseExited

    private void jLabel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseEntered
        jPanel4.setVisible(false);
        jLabel11.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_jLabel11MouseEntered

    private void jLabel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseExited
        jLabel11.setBackground(R);
    }//GEN-LAST:event_jLabel11MouseExited

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        expandedbar.setVisible(true);
         collapsedbar.setVisible(false);
         jLabel1.setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
         jLabel4.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
         jLabel4.setBackground(R);
    }//GEN-LAST:event_jLabel4MouseExited

    private void add_instMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_instMouseEntered
         add_inst.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_add_instMouseEntered

    private void add_instMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_instMouseExited
         add_inst.setBackground(R);
    }//GEN-LAST:event_add_instMouseExited

    private void add_studMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_studMouseEntered
       add_stud.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_add_studMouseEntered

    private void add_studMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_studMouseExited
         add_stud.setBackground(R);
    }//GEN-LAST:event_add_studMouseExited

    private void homepanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homepanelMouseEntered
        jPanel4.setVisible(false);
    }//GEN-LAST:event_homepanelMouseEntered

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
          student.setVisible(false);
         homepanel.setVisible(true);
        addpanel.setVisible(false);
        admin.setVisible(false);
        instructor.setVisible(false);
        exampanel.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
         student.setVisible(false);
         homepanel.setVisible(true);
        addpanel.setVisible(false);
        admin.setVisible(false);
        instructor.setVisible(false);
        exampanel.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
         jPanel4.setVisible(false);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
         student.setVisible(false);
         homepanel.setVisible(false);
        addpanel.setVisible(false);
        admin.setVisible(true);
        instructor.setVisible(false);
        exampanel.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jLabel18MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseEntered
        jLabel18.setOpaque(true);
        jLabel18.setBackground(java.awt.Color.GRAY);
        admin_pass.setEchoChar((char)0);
    }//GEN-LAST:event_jLabel18MouseEntered

    private void jLabel18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseExited
        jLabel18.setOpaque(false);
        jLabel18.setBackground(java.awt.Color.WHITE);
        admin_pass.setEchoChar('*');
    }//GEN-LAST:event_jLabel18MouseExited

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        student.setVisible(false);
         homepanel.setVisible(false);
        addpanel.setVisible(false);
        admin.setVisible(true);
        instructor.setVisible(false);
        exampanel.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
      student.setVisible(false);
         homepanel.setVisible(false);
        addpanel.setVisible(true);
        admin.setVisible(false);
        instructor.setVisible(false);
        exampanel.setVisible(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
       student.setVisible(true);
         homepanel.setVisible(false);
        addpanel.setVisible(true);
        admin.setVisible(false);
        instructor.setVisible(false);
        exampanel.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        student.setVisible(false);
         homepanel.setVisible(false);
        addpanel.setVisible(false);
        admin.setVisible(false);
        instructor.setVisible(true);
        exampanel.setVisible(false);
    }//GEN-LAST:event_jButton2MouseClicked

    private void add_instMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_instMouseClicked
        homepanel.setVisible(false);
        addpanel.setVisible(false);
        admin.setVisible(false);
        instructor.setVisible(true);
        student.setVisible(false);
        exampanel.setVisible(false);
        
        j.instReqTable = (DefaultTableModel)req_table.getModel();
        j.instListTable = (DefaultTableModel)inst_list.getModel();
        if(r.reg){
            j.showInstData();
            j.instData();
            r.reg = false;
        }
        
    }//GEN-LAST:event_add_instMouseClicked

    private void adminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseEntered
        jPanel4.setVisible(false);
    }//GEN-LAST:event_adminMouseEntered

    private void add_studMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_studMouseClicked
        student.setVisible(true);
         homepanel.setVisible(false);
        addpanel.setVisible(false);
        admin.setVisible(false);
        instructor.setVisible(false);
        exampanel.setVisible(false);
        j.studReqTable = (DefaultTableModel)stud_req.getModel();
        j.studListTable = (DefaultTableModel)stud_list.getModel();
        if(r.reg2){
            j.showStudData();
            j.studData();
            r.reg2 = false;
        }
    }//GEN-LAST:event_add_studMouseClicked

    private void studentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentMouseEntered
        jPanel4.setVisible(false);
    }//GEN-LAST:event_studentMouseEntered

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        student.setVisible(true);
         homepanel.setVisible(false);
        addpanel.setVisible(false);
        admin.setVisible(false);
        instructor.setVisible(false);
        exampanel.setVisible(false);
    }//GEN-LAST:event_jButton3MouseClicked

    private void examLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examLabelMouseClicked
        exampanel.setVisible(true);
        student.setVisible(false);
         homepanel.setVisible(false);
        addpanel.setVisible(false);
        admin.setVisible(false);
        instructor.setVisible(false);
        j.studentNames = (DefaultTableModel)studTable.getModel();
        j.sessionsTable = (DefaultTableModel)sessionTable.getModel();
        for (int i = studTable.getModel().getRowCount()-1; i >= 0; i--) {
            j.studentNames.removeRow(i);
        }
        for (int i = sessionTable.getModel().getRowCount()-1; i >= 0; i--) {
            j.sessionsTable.removeRow(i);
        }
        j.showSessions();
        j.studentsNames();
    }//GEN-LAST:event_examLabelMouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        exampanel.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void exampanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exampanelMouseEntered
        jPanel4.setVisible(false);
    }//GEN-LAST:event_exampanelMouseEntered

    private void jScrollPane1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseEntered
        jPanel4.setVisible(false);
    }//GEN-LAST:event_jScrollPane1MouseEntered

    private void jScrollPane2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseEntered
        jPanel4.setVisible(false);
    }//GEN-LAST:event_jScrollPane2MouseEntered

    private void req_tableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_req_tableMouseEntered
        jPanel4.setVisible(false);
    }//GEN-LAST:event_req_tableMouseEntered

    private void instructorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instructorMouseEntered
        jPanel4.setVisible(false);
        
    }//GEN-LAST:event_instructorMouseEntered

    private void btn_studMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_studMouseClicked
         student.setVisible(true);
         homepanel.setVisible(false);
        addpanel.setVisible(false);
        admin.setVisible(false);
        instructor.setVisible(false);
        exampanel.setVisible(false);
        j.studReqTable = (DefaultTableModel)stud_req.getModel();
        j.studListTable = (DefaultTableModel)stud_list.getModel();
        if(r.reg2){
            j.showStudData();
            j.studData();
            r.reg2 = false;
        }
    }//GEN-LAST:event_btn_studMouseClicked

    private void btn_instMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_instMouseClicked
         student.setVisible(false);
         homepanel.setVisible(false);
        addpanel.setVisible(false);
        admin.setVisible(false);
        instructor.setVisible(true);
        exampanel.setVisible(false);
        j.instReqTable = (DefaultTableModel)req_table.getModel();
        j.instListTable = (DefaultTableModel)inst_list.getModel();
        if(r.reg){
            j.showInstData();
            j.instData();
            r.reg = false;
        }
    }//GEN-LAST:event_btn_instMouseClicked

    private void examBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_examBtnMouseClicked
        student.setVisible(false);
         homepanel.setVisible(false);
        addpanel.setVisible(false);
        admin.setVisible(false);
        instructor.setVisible(false);
        exampanel.setVisible(true);
    }//GEN-LAST:event_examBtnMouseClicked

    private void admin_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_passActionPerformed

    private void add_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_adminActionPerformed
        // TODO add your handling code here:
        j.adminName = admin_name.getText();
        j.adminPass = admin_pass.getText();
        j.add_admin(j);
        admin_name.setText("");
        admin_pass.setText("");
    }//GEN-LAST:event_add_adminActionPerformed

    private void btn_instActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_instActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_instActionPerformed

    private void add_insActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_insActionPerformed
        // TODO add your handling code here:
        try{
            for (int i = 0; i < req_table.getModel().getRowCount(); i++) {
                j.ID = (int)req_table.getModel().getValueAt(i,0);
                j.usName = (String)req_table.getModel().getValueAt(i,1);
                j.mail = (String)req_table.getModel().getValueAt(i,2);
            }
            int selectedRow = req_table.getSelectedRow();
            for (int i = inst_list.getModel().getRowCount()-1; i>=0; i--) {
                j.instListTable.removeRow(i);
            }
            for (int i = req_table.getModel().getRowCount()-1; i >=0 ; i--) {
                j.instReqTable.removeRow(i);
            }
            j.addInst(selectedRow);
            j.instData();
            j.showInstData();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_add_insActionPerformed

    private void del_insActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_del_insActionPerformed
        // TODO add your handling code here:
        try{
            for (int i = 0; i < req_table.getModel().getRowCount(); i++) {
                j.ID = (int)req_table.getModel().getValueAt(i,0);
            }
            for (int i = req_table.getModel().getRowCount()-1; i >=0 ; i--) {
                j.instReqTable.removeRow(i);
            }
            int selectedrow = req_table.getSelectedRow();
            j.deleteInst(selectedrow);
            j.showInstData();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_del_insActionPerformed

    private void addstudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudActionPerformed
        // TODO add your handling code here:
        try{
            for (int i = 0; i < stud_req.getModel().getRowCount(); i++) {
                j.ID = (int)stud_req.getModel().getValueAt(i,0);
                j.usName = (String)stud_req.getModel().getValueAt(i,1);
                j.mail = (String)stud_req.getModel().getValueAt(i,2);
            }
            int selectedRow = stud_req.getSelectedRow();
            for (int i = stud_list.getModel().getRowCount()-1; i >= 0; i--) {
                j.studListTable.removeRow(i);
            }
            for (int i = stud_req.getModel().getRowCount()-1; i >= 0; i--) {
                j.studReqTable.removeRow(i);
            }
            j.addStud(selectedRow);
            j.studData();
            j.showStudData();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_addstudActionPerformed

    private void delstudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delstudActionPerformed
        // TODO add your handling code here:
        try{
            for (int i = 0; i < stud_req.getModel().getRowCount(); i++) {
                j.ID = (int)stud_req.getModel().getValueAt(i,0);
            }
            for (int i = stud_req.getModel().getRowCount()-1; i >=0 ; i--) {
                j.studReqTable.removeRow(i);
            }
            int selectedrow = stud_req.getSelectedRow();
            j.deleteStud(selectedrow);
            j.showStudData();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_delstudActionPerformed

    private void jScrollPane7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane7MouseEntered

    private void examBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examBtnActionPerformed
        // TODO add your handling code here:
        j.studentNames = (DefaultTableModel)studTable.getModel();
        j.sessionsTable = (DefaultTableModel)sessionTable.getModel();
        for (int i = studTable.getModel().getRowCount()-1; i >= 0; i--) {
            j.studentNames.removeRow(i);
        }
        for (int i = sessionTable.getModel().getRowCount()-1; i >= 0; i--) {
            j.sessionsTable.removeRow(i);
        }
        j.showSessions();
        j.studentsNames();
    }//GEN-LAST:event_examBtnActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int selectedRow = sessionTable.getSelectedRow();
        int selectedRow2 = studTable.getSelectedRow();
        j.studName = (String)studTable.getModel().getValueAt(selectedRow2, 0);
        Emergency.ID = (int)sessionTable.getModel().getValueAt(selectedRow, 1);
        j.addSession(selectedRow, selectedRow2);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void openBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBtnActionPerformed
        // TODO add your handling code here:
        j.sessionsTable = (DefaultTableModel)sessionTable.getModel();
        int selectedRow = sessionTable.getSelectedRow();
        Emergency.ID = (int)sessionTable.getModel().getValueAt(selectedRow, 1);
        j.sessionsTable.setValueAt("open",selectedRow, 2);
        j.updateAcceptance(selectedRow);
    }//GEN-LAST:event_openBtnActionPerformed
           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_admin;
    private javax.swing.JButton add_ins;
    private javax.swing.JLabel add_inst;
    private javax.swing.JLabel add_stud;
    private javax.swing.JPanel addpanel;
    private javax.swing.JButton addstud;
    private javax.swing.JPanel admin;
    private javax.swing.JTextField admin_name;
    private javax.swing.JPasswordField admin_pass;
    private javax.swing.JButton btn_inst;
    private javax.swing.JButton btn_stud;
    private javax.swing.JPanel collapsedbar;
    private javax.swing.JButton del_ins;
    private javax.swing.JButton delstud;
    private javax.swing.JButton examBtn;
    private javax.swing.JLabel examLabel;
    private javax.swing.JPanel exampanel;
    private javax.swing.JPanel expandedbar;
    private javax.swing.JPanel homepanel;
    private javax.swing.JTable inst_list;
    private javax.swing.JPanel instructor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable5;
    private javax.swing.JButton openBtn;
    private javax.swing.JTable req_table;
    private javax.swing.JTable sessionTable;
    private javax.swing.JTable studTable;
    private javax.swing.JTable stud_list;
    private javax.swing.JTable stud_req;
    private javax.swing.JPanel student;
    // End of variables declaration//GEN-END:variables
}
